# Generated by Django 4.2.4 on 2023-08-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_watchlist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='profile_pics',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_pics',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pics',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
