# Generated by Django 4.2.4 on 2023-08-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_pics',
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='profile_pics',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_pics',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
