# Generated by Django 4.2.4 on 2023-09-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
