# Generated by Django 4.2.4 on 2023-09-05 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_category_parent_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.topic'),
        ),
    ]
